stages:
  - build
variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
docker-build:
  only:
      refs:
        - dev
        - master
  stage: build
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]
    - docker:dind
  before_script:
   - echo $CI_REGISTRY
   - docker login -u $CI_TKN_LN -p $CI_TKN_PW $CI_REGISTRY
  script:
    - docker logout
    #- docker build --pull --build-arg HTTP_PROXY=$SHTTP_PROXY --build-arg HTTPS_PROXY=$SHTTPS_PROXY -t $TAG_LATEST . 
    - docker build --pull -t $TAG_LATEST . 
    - docker login -u $CI_TKN_LN -p $CI_TKN_PW $CI_REGISTRY
    - docker images
    - echo $DOCKER_IMAGE_NAME 
    - echo $CI_REGISTRY_IMAGE:latest
    - docker tag $TAG_LATEST $CI_REGISTRY_IMAGE/master:latest
    - docker push $TAG_LATEST

