stages:
 - test
 - cleanup

variables:
 TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
 TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
 POETRY_VERSION: 2.1.1
 # Прокси настройки
 HTTP_PROXY: http://proxy.server:8080
 HTTPS_PROXY: http://proxy.server:8080
 NO_PROXY: localhost,127.0.0.1

test:
 stage: test
 image: python:3.11-slim
 cache:
 key: poetry-$CI_COMMIT_REF_NAME
 paths:
 -.venv/
 - poetry.lock
 before_script:
 - export HTTP_PROXY=$HTTP_PROXY
 - export HTTPS_PROXY=$HTTPS_PROXY
 - export NO_PROXY=$NO_PROXY
 - pip install poetry==$POETRY_VERSION
 - poetry config virtualenvs.in-project true
 - poetry config http.proxy $HTTP_PROXY
 - poetry config http.https $HTTPS_PROXY
 - poetry install --only main
 script:
 - poetry run pytest
 - poetry run coverage report
 rules:
 - if: $CI_COMMIT_BRANCH == 'dev'
 - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
 - if: $CI_COMMIT_BRANCH == 'master'

cleanup:
 stage: cleanup
 script:
 - rm -rf.venv
 - rm poetry.lock
 when: always
 except:
 - merge_requests

workflow:
 rules:
 - if: $CI_COMMIT_BRANCH == 'dev'
 - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
 - if: $CI_COMMIT_BRANCH == 'master'