services:
  gpt-db:
    build:
      context: .
      args:
        - SHTTP_PROXY=${SHTTP_PROXY}
        - SHTTPS_PROXY=${SHTTPS_PROXY}
        - HTTP_PROXY=${SHTTP_PROXY}
        - HTTPS_PROXY=${SHTTPS_PROXY}
    container_name: gpt-db
    restart: unless-stopped
    env_file:
      - .env
    #ports:
    #  - "8501:8501"
    volumes:
      - .:/app
      - /app/.venv
      
  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123